### ISSUE TITLE
I copied this code and now my professor gave me an F

### ISSUE THREAD

**Issue by mujtaba-io** [HasaanAhmad/Object-Oriented-Programming-Lab-Manual-Comsats-University-Islamabad#1]
Whay did you do that :-(

**Comment by HasaanAhmad** [comment]
Try changing variable names next time. Avg Solution to trick professors of OHIO.

**Comment by mujtaba-io** [comment]
But why did he said "better not fool me next time using copilot" (in rough voice) 😣😣 please fix the issue

**Comment by HasaanAhmad** [comment]
Irony is He can't afford copilot! That's why!

**Comment by mujtaba-io** [comment]
Yes I believe you are right.
